### ISSUE TITLE
Getting a scrollbar

### ISSUE THREAD

**Issue by mlcampbe** [vincep5/MMM-DarkSkyRadar#2]
If I change the height of the module from the default 600px to 500px I am getting a scrollbar to show up on the right-hand side for some reason. I see that the .css file has -webkit-scrollbar set to none but I still see it. This only occurs if I make the height less than the default of 600px. 

Oddly enough this only occurs on my dedicated monitor that is rotated 90 degrees for "portrait" mode. If I access the same setup using the browser there is no scrollbar displayed.

Any ideas?

**Comment by vincep5** [comment]
on line 29 you can add 
iframe.scrolling = "no"

in the file MMM-DarkSkyRadar.js   Try it out.  If that works, I can check in the change for everyone.
Thanks

**Comment by mlcampbe** [comment]
Yes I can confirm that adding "iframe.scrolling = "no;" does resolve the problem.

**Comment by vincep5** [comment]
Thanks for testing.  I have committed the change
